AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Auth:
        ApiKeyRequired: True
      StageName: v1

  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: asg-ip-obtainer/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        GetIps:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref Api
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ec2:Describe*
                - autoscaling:Describe*
              Resource: "*"


Outputs:
  Api:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/v1/"
